name: First Workflow
on: workflow_dispatch
jobs:
  first-jobs:
    runs-on: windows-2019
    steps:
     - name: Print greeting
       run: echo "Hello World"
     - name: Print greeting
       run: echo "done - bye"
